const Logos = {
  MaaFW: () => import("./maafw.png"),
  M9A: () => import("./m9a.png"),
  MSBA: () => import("./msba.png"),
  MaaYYs: () => import("./maayys.png"),
  MPA: () => import("./mpa.png"),
  MaaYuan: () => import("./maayuan.png"),
  MaaGF2Exilium: () => import("./maagf2exilium.png"),
  MaaGumballs: () => import("./maagumballs.ico"),
  MaaHBR: () => import("./maahbr.png"),
  MaaTOT: () => import("./maatot.png"),
  MMleo: () => import("./mmleo.png"),
  SLIMEIM_Maa: () => import("./slimeim_maa.ico"),
  MFWPyQt6: () => import("./mfwpyqt6.png"),
  MFA: () => import("./mfa.png"),
  Maabbb: () => import("./maabbb.ico"),
  MPE: () => import("./mpe.png"),
  MAN: () => import("./man.png"),
  MaaGakumasu: () => import("./MaaGakumasu.png"),
  MaaStarResonance: () => import("./MaaStarResonance.png"),
  MAAAE: () => import("./maaae.png"),
  MBCCTools: () => import("./mbcctools.jpg"),
  MaaEOV: () => import("./maaeov.png"),
  MAALogAnalyzer: () => import("./mla.png"),
  StellaSoraAutoHelper: () => import("./ssah.png"),
  MaaDuDuL: () => import("./mddl.png"),
  MaaLYSK: () => import("./maalysk.webp"),
};

export default Logos;
