name: Deploy

on:
  push:
    branches: [main] # Dev
  workflow_dispatch:

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Docs
        uses: actions/checkout@v4
        with:
          repository: MaaXYZ/MaaFramework
          path: ./raw
          sparse-checkout: |
            docs

      - name: Prepare Docs
        run: |
          cd src
          cp -r ../raw/docs/zh_cn/* docs
          cp -r ../raw/docs/en_us/* en/docs

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build with VitePress
        run: yarn build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          TARGET: ${{ secrets.DEPLOY_PATH }}
          SOURCE: src/.vitepress/dist
          # ARGS: -avzr --delete
